name: Cypress Tests

on:
  push:
    branches:
      - master  # Cambia a 'master' si tu rama principal se llama así
  pull_request:
    branches:
      - master  # Cambia a 'master' si tu rama principal se llama así

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Usa la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests on Chrome
        run: npm test -- --browser chrome

      - name: Run Cypress tests on Firefox
        run: npm test -- --browser firefox

      - name: Generate test report
        run: npx cypress run --reporter cypress-mochawesome-reporter

      - name: Upload test report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: cypress-report
          path: cypress/reports/  
          